### ISSUE TITLE
Invalid Token Error When Hitting Endpoint

### ISSUE THREAD

**Issue by nikhil478** [bitcoin-sv/block-headers-service#259]
Description

I followed the documentation to run the block-headers-service using Docker:
docker pull bsvb/block-headers-service
docker run -e HTTP_SERVER_AUTHTOKEN=HELLOWORLD -p 8080:8080 bsvb/block-headers-service:latest
However, when I try to hit the endpoint with the same AUTHTOKEN, I receive an "Invalid Token" error.

Steps to Reproduce

Run the following commands to start the service:
docker pull bsvb/block-headers-service
docker run -e HTTP_SERVER_AUTHTOKEN=HELLOWORLD -p 8080:8080 bsvb/block-headers-service:latest
Attempt to hit the endpoint using the token HELLOWORLD.

**Expected behavior**
The endpoint should accept the token and return the appropriate response.

**Logs**
If you have any logs connected with your problem - please attach them.

**Screenshots**

**Used environment (please complete the following information):**

- Device: [gitpod]
- OS: [linux]
- Browser [brave]
[
![Screenshot (210)](https://github.com/bitcoin-sv/block-headers-service/assets/67046318/55aabbb1-0fe0-4f2b-825c-a521210ab4a7)
![Screenshot (211)](https://github.com/bitcoin-sv/block-headers-service/assets/67046318/ee379c9c-6cda-4ced-913f-979329ff660b)
](url)
**Additional context**
Please let me know if there are any additional configurations or steps required that might be missing from the documentation.

**Comment by nikhil478** [comment]
@jadwahab @mwilkosinski @proapi @sirdeggen

**Comment by dorzepowski** [comment]
@nikhil478 We checked your issue and it occurs that the README info was a little bit out of date.
The correct name of the environment variable should be `BHS_HTTP_AUTH_TOKEN`,
so the proper command would be:
 ```bash
docker run -e BHS_HTTP_AUTH_TOKEN=HELLOWORLD -p 8080:8080 bsvb/block-headers-service:latest
```

**Comment by nikhil478** [comment]
this works thanks @dorzepowski
